// ===== 2025 F1 SEASON DATA =====

const F1_TEAMS = [
  {
    id: "redbull",
    name: "Red Bull Racing",
    shortName: "RED BULL",
    color: "#3671C6",
    accentColor: "#CC1E4A",
    base: "Milton Keynes, UK",
    principal: "Christian Horner",
    championships: 6,
    powerUnit: "Honda RBPT",
    chassis: "RB21",
    firstEntry: 2005,
    description: "The dominant force in modern F1, Red Bull Racing has redefined championship success with their technical brilliance and Max Verstappen at the wheel.",
    drivers: ["max-verstappen", "liam-lawson"]
  },
  {
    id: "ferrari",
    name: "Scuderia Ferrari",
    shortName: "FERRARI",
    color: "#E8002D",
    accentColor: "#FFDD00",
    base: "Maranello, Italy",
    principal: "Frédéric Vasseur",
    championships: 16,
    powerUnit: "Ferrari",
    chassis: "SF-25",
    firstEntry: 1950,
    description: "The most iconic team in Formula 1, Scuderia Ferrari is the beating heart of the sport. With 16 Constructors' titles and legendary history, the Prancing Horse remains the most iconic brand in racing.",
    drivers: ["charles-leclerc", "lewis-hamilton"]
  },
  {
    id: "mercedes",
    name: "Mercedes-AMG Petronas",
    shortName: "MERCEDES",
    color: "#27F4D2",
    accentColor: "#FFFFFF",
    base: "Brackley, UK",
    principal: "Toto Wolff",
    championships: 8,
    powerUnit: "Mercedes",
    chassis: "W16",
    firstEntry: 2010,
    description: "Eight consecutive Constructors' Championships cemented Mercedes as the most successful team in the modern era. Now rebuilding around young talent for the next chapter.",
    drivers: ["george-russell", "andrea-kimi-antonelli"]
  },
  {
    id: "mclaren",
    name: "McLaren F1 Team",
    shortName: "McLAREN",
    color: "#FF8000",
    accentColor: "#000000",
    base: "Woking, UK",
    principal: "Andrea Stella",
    championships: 8,
    powerUnit: "Mercedes",
    chassis: "MCL39",
    firstEntry: 1966,
    description: "After years of rebuilding, McLaren has surged back to the front of the grid and secured the 2024 Constructors' Championship. The papaya wave is back.",
    drivers: ["lando-norris", "oscar-piastri"]
  },
  {
    id: "astonmartin",
    name: "Aston Martin Aramco",
    shortName: "ASTON MARTIN",
    color: "#229971",
    accentColor: "#CEDC00",
    base: "Silverstone, UK",
    principal: "Mike Krack",
    championships: 0,
    powerUnit: "Mercedes",
    chassis: "AMR25",
    firstEntry: 2018,
    description: "Backed by Lawrence Stroll's investment, Aston Martin is building toward championship contention with Adrian Newey now onboard and Fernando Alonso's vast experience.",
    drivers: ["fernando-alonso", "lance-stroll"]
  },
  {
    id: "alpine",
    name: "BWT Alpine F1 Team",
    shortName: "ALPINE",
    color: "#FF87BC",
    accentColor: "#0090FF",
    base: "Enstone, UK",
    principal: "Oliver Oakes",
    championships: 2,
    powerUnit: "Renault",
    chassis: "A525",
    firstEntry: 2021,
    description: "Alpine, born from the ashes of Renault F1, fights with Gallic determination as the only French works team on the grid.",
    drivers: ["pierre-gasly", "jack-doohan"]
  },
  {
    id: "haas",
    name: "MoneyGram Haas F1 Team",
    shortName: "HAAS",
    color: "#B6BABD",
    accentColor: "#E8002D",
    base: "Kannapolis, USA",
    principal: "Ayao Komatsu",
    championships: 0,
    powerUnit: "Ferrari",
    chassis: "VF-25",
    firstEntry: 2016,
    description: "America's only team in Formula 1, Haas punches above its weight as a customer-model constructor powered by Ferrari.",
    drivers: ["esteban-ocon", "oliver-bearman"]
  },
  {
    id: "rb",
    name: "Visa Cash App RB",
    shortName: "RACING BULLS",
    color: "#6692FF",
    accentColor: "#FFFFFF",
    base: "Faenza, Italy",
    principal: "Laurent Mekies",
    championships: 0,
    powerUnit: "Honda RBPT",
    chassis: "VCARB 02",
    firstEntry: 1985,
    description: "Red Bull's junior outfit serves as the proving ground for future champions, competing with Honda power and a talented young lineup.",
    drivers: ["yuki-tsunoda", "isack-hadjar"]
  },
  {
    id: "williams",
    name: "Williams Racing",
    shortName: "WILLIAMS",
    color: "#64C4FF",
    accentColor: "#FFFFFF",
    base: "Grove, UK",
    principal: "James Vowles",
    championships: 9,
    powerUnit: "Mercedes",
    chassis: "FW47",
    firstEntry: 1977,
    description: "A storied team with nine Constructors' Championships, Williams is on a resurgence under new leadership, aiming to restore former glories.",
    drivers: ["alex-albon", "carlos-sainz"]
  },
  {
    id: "kicksauber",
    name: "Stake F1 Team Kick Sauber",
    shortName: "KICK SAUBER",
    color: "#52E252",
    accentColor: "#000000",
    base: "Hinwil, Switzerland",
    principal: "Mattia Binotto",
    championships: 0,
    powerUnit: "Ferrari",
    chassis: "C45",
    firstEntry: 1993,
    description: "In transition to become Audi's works team from 2026, Kick Sauber is laying the groundwork for a bold new chapter in Swiss F1 history.",
    drivers: ["nico-hulkenberg", "gabriel-bortoleto"]
  },
  {
    id: "moneygram",
    name: "Andretti Global (Cadillac)",
    shortName: "CADILLAC",
    color: "#BA2D4A",
    accentColor: "#DDC04B",
    base: "Silverstone, UK",
    principal: "Graeme Lowdon",
    championships: 0,
    powerUnit: "Ferrari",
    chassis: "AGX01",
    firstEntry: 2025,
    description: "The newest team to join the Formula 1 grid, Andretti Global with Cadillac backing marks America's ambitious return as a constructor to the pinnacle of motorsport.",
    drivers: ["colton-herta", "marcus-armstrong"]
  }
];

const F1_DRIVERS = [
  // Red Bull
  {
    id: "max-verstappen",
    name: "Max Verstappen",
    shortName: "VERSTAPPEN",
    nationality: "🇳🇱 Dutch",
    number: 1,
    team: "redbull",
    age: 27,
    podiums: 106,
    wins: 62,
    championships: 4,
    points: 0,
    bio: "Four-time World Champion. The youngest ever champion in F1 history. Verstappen's raw pace and racecraft have made him the benchmark of his generation.",
    initials: "MV"
  },
  {
    id: "liam-lawson",
    name: "Liam Lawson",
    shortName: "LAWSON",
    nationality: "🇳🇿 New Zealander",
    number: 30,
    team: "redbull",
    age: 22,
    podiums: 0,
    wins: 0,
    championships: 0,
    points: 0,
    bio: "Promoted to Red Bull's senior team after impressive performances, New Zealand's Liam Lawson is considered one of the most exciting young talents in the sport.",
    initials: "LL"
  },
  // Ferrari
  {
    id: "charles-leclerc",
    name: "Charles Leclerc",
    shortName: "LECLERC",
    nationality: "🇲🇨 Monégasque",
    number: 16,
    team: "ferrari",
    age: 27,
    podiums: 42,
    wins: 8,
    championships: 0,
    points: 0,
    bio: "The face of Ferrari's future, Leclerc's blazing qualifying pace and flair on street circuits has earned him iconic status at the Scuderia.",
    initials: "CL"
  },
  {
    id: "lewis-hamilton",
    name: "Lewis Hamilton",
    shortName: "HAMILTON",
    nationality: "🇬🇧 British",
    number: 44,
    team: "ferrari",
    age: 40,
    podiums: 202,
    wins: 104,
    championships: 7,
    points: 0,
    bio: "Seven-time World Champion and the most decorated driver in F1 history. Hamilton made the stunning move to Ferrari for 2025, sparking enormous excitement worldwide.",
    initials: "LH"
  },
  // Mercedes
  {
    id: "george-russell",
    name: "George Russell",
    shortName: "RUSSELL",
    nationality: "🇬🇧 British",
    number: 63,
    team: "mercedes",
    age: 27,
    podiums: 18,
    wins: 3,
    championships: 0,
    points: 0,
    bio: "Mr. Saturday. Known for his extraordinary qualifying ability, Russell now leads Mercedes' charge as their undisputed number one driver.",
    initials: "GR"
  },
  {
    id: "andrea-kimi-antonelli",
    name: "Andrea Kimi Antonelli",
    shortName: "ANTONELLI",
    nationality: "🇮🇹 Italian",
    number: 12,
    team: "mercedes",
    age: 18,
    podiums: 0,
    wins: 0,
    championships: 0,
    points: 0,
    bio: "The most hyped F1 rookie in years, Antonelli is Mercedes' chosen one — a teenage prodigy tipped to become a future World Champion.",
    initials: "KA"
  },
  // McLaren
  {
    id: "lando-norris",
    name: "Lando Norris",
    shortName: "NORRIS",
    nationality: "🇬🇧 British",
    number: 4,
    team: "mclaren",
    age: 25,
    podiums: 27,
    wins: 4,
    championships: 0,
    points: 0,
    bio: "McLaren's leader, Lando Norris combines electric pace with a massive fan following. After his breakthrough 2024 campaign, 2025 is his year to challenge for the title.",
    initials: "LN"
  },
  {
    id: "oscar-piastri",
    name: "Oscar Piastri",
    shortName: "PIASTRI",
    nationality: "🇦🇺 Australian",
    number: 81,
    team: "mclaren",
    age: 23,
    podiums: 16,
    wins: 4,
    championships: 0,
    points: 0,
    bio: "Ice-cool Australian who's taken to F1 like a natural. Piastri is already considered one of the most complete drivers on the grid despite being just in his second year.",
    initials: "OP"
  },
  // Aston Martin
  {
    id: "fernando-alonso",
    name: "Fernando Alonso",
    shortName: "ALONSO",
    nationality: "🇪🇸 Spanish",
    number: 14,
    team: "astonmartin",
    age: 43,
    podiums: 106,
    wins: 32,
    championships: 2,
    points: 0,
    bio: "The Indestructible One. Fernando Alonso continues to defy age and time, remaining one of the most ferocious competitors on the grid with two World Championships.",
    initials: "FA"
  },
  {
    id: "lance-stroll",
    name: "Lance Stroll",
    shortName: "STROLL",
    nationality: "🇨🇦 Canadian",
    number: 18,
    team: "astonmartin",
    age: 26,
    podiums: 3,
    wins: 0,
    championships: 0,
    points: 0,
    bio: "Canadian driver and son of team owner Lawrence Stroll, Lance has shown genuine pace when conditions suit him, including famous podiums in unpredictable races.",
    initials: "LS"
  },
  // Alpine
  {
    id: "pierre-gasly",
    name: "Pierre Gasly",
    shortName: "GASLY",
    nationality: "🇫🇷 French",
    number: 10,
    team: "alpine",
    age: 29,
    podiums: 4,
    wins: 1,
    championships: 0,
    points: 0,
    bio: "Italian GP winner and fan favourite, Gasly brings aggression and determination to Alpine as the team's experienced spearhead.",
    initials: "PG"
  },
  {
    id: "jack-doohan",
    name: "Jack Doohan",
    shortName: "DOOHAN",
    nationality: "🇦🇺 Australian",
    number: 7,
    team: "alpine",
    age: 22,
    podiums: 0,
    wins: 0,
    championships: 0,
    points: 0,
    bio: "Son of MotoGP legend Mick Doohan, Jack brings his own identity to racing — a feisty young talent making his mark in Grand Prix racing.",
    initials: "JD"
  },
  // Haas
  {
    id: "esteban-ocon",
    name: "Esteban Ocon",
    shortName: "OCON",
    nationality: "🇫🇷 French",
    number: 31,
    team: "haas",
    age: 28,
    podiums: 2,
    wins: 1,
    championships: 0,
    points: 0,
    bio: "Hungarian GP winner and gritty competitor, Ocon joins Haas looking to reignite his career and show what he can do with a fresh start.",
    initials: "EO"
  },
  {
    id: "oliver-bearman",
    name: "Oliver Bearman",
    shortName: "BEARMAN",
    nationality: "🇬🇧 British",
    number: 87,
    team: "haas",
    age: 19,
    podiums: 0,
    wins: 0,
    championships: 0,
    points: 0,
    bio: "British teenage talent who made a sensational debut for Ferrari in Saudi Arabia 2024, Bearman is now a full-time starter with Haas.",
    initials: "OB"
  },
  // Racing Bulls
  {
    id: "yuki-tsunoda",
    name: "Yuki Tsunoda",
    shortName: "TSUNODA",
    nationality: "🇯🇵 Japanese",
    number: 22,
    team: "rb",
    age: 24,
    podiums: 0,
    wins: 0,
    championships: 0,
    points: 0,
    bio: "Japan's fastest export, Tsunoda has grown enormously since his debut, maturing into a combative qualifier and racer with Honda power.",
    initials: "YT"
  },
  {
    id: "isack-hadjar",
    name: "Isack Hadjar",
    shortName: "HADJAR",
    nationality: "🇫🇷 French",
    number: 6,
    team: "rb",
    age: 20,
    podiums: 0,
    wins: 0,
    championships: 0,
    points: 0,
    bio: "Franco-Algerian Formula 2 champion stepping up to F1 with Racing Bulls — a precise, tactical racer known for exceptional race management.",
    initials: "IH"
  },
  // Williams
  {
    id: "alex-albon",
    name: "Alexander Albon",
    shortName: "ALBON",
    nationality: "🇹🇭 Thai",
    number: 23,
    team: "williams",
    age: 28,
    podiums: 2,
    wins: 0,
    championships: 0,
    points: 0,
    bio: "Tenacious and consistent, Albon is the backbone of Williams' revival — consistently extracting points from a car that often isn't the fastest.",
    initials: "AA"
  },
  {
    id: "carlos-sainz",
    name: "Carlos Sainz",
    shortName: "SAINZ",
    nationality: "🇪🇸 Spanish",
    number: 55,
    team: "williams",
    age: 30,
    podiums: 23,
    wins: 3,
    championships: 0,
    points: 0,
    bio: "After leaving Ferrari, Smooth Operator Carlos Sainz chose Williams for 2025 — his ambition being to elevate the team back to championship contention.",
    initials: "CS"
  },
  // Kick Sauber
  {
    id: "nico-hulkenberg",
    name: "Nico Hülkenberg",
    shortName: "HULKENBERG",
    nationality: "🇩🇪 German",
    number: 27,
    team: "kicksauber",
    age: 37,
    podiums: 0,
    wins: 0,
    championships: 0,
    points: 0,
    bio: "The most experienced driver never to win an F1 race, Hulkenberg is the seasoned veteran leading Sauber's transition as the future Audi works team shapes up.",
    initials: "NH"
  },
  {
    id: "gabriel-bortoleto",
    name: "Gabriel Bortoleto",
    shortName: "BORTOLETO",
    nationality: "🇧🇷 Brazilian",
    number: 5,
    team: "kicksauber",
    age: 20,
    podiums: 0,
    wins: 0,
    championships: 0,
    points: 0,
    bio: "F2 and F3 champion Gabriel Bortoleto is the hottest property from Brazil in F1 since the legendary Senna — calm, technically brilliant, and ice cold under pressure.",
    initials: "GB"
  },
  // Cadillac
  {
    id: "colton-herta",
    name: "Colton Herta",
    shortName: "HERTA",
    nationality: "🇺🇸 American",
    number: 2,
    team: "moneygram",
    age: 24,
    podiums: 0,
    wins: 0,
    championships: 0,
    points: 0,
    bio: "IndyCar star Colton Herta fulfils his F1 dream with Andretti Cadillac — America's new hero gunning for points in the premier class of motorsport.",
    initials: "CH"
  },
  {
    id: "marcus-armstrong",
    name: "Marcus Armstrong",
    shortName: "ARMSTRONG",
    nationality: "🇳🇿 New Zealander",
    number: 45,
    team: "moneygram",
    age: 24,
    podiums: 0,
    wins: 0,
    championships: 0,
    points: 0,
    bio: "IndyCar race-winner Marcus Armstrong joins Cadillac alongside Herta — the Kiwi racer ready to take on F1's elite on the world stage.",
    initials: "MA"
  }
];

// Simulated standings (pre-season estimated)
const DRIVER_STANDINGS = [
  { pos: 1, name: "Max Verstappen", team: "redbull", points: 0, color: "#3671C6" },
  { pos: 2, name: "Charles Leclerc", team: "ferrari", points: 0, color: "#E8002D" },
  { pos: 3, name: "Lewis Hamilton", team: "ferrari", points: 0, color: "#E8002D" },
  { pos: 4, name: "Lando Norris", team: "mclaren", points: 0, color: "#FF8000" },
  { pos: 5, name: "Oscar Piastri", team: "mclaren", points: 0, color: "#FF8000" },
  { pos: 6, name: "George Russell", team: "mercedes", points: 0, color: "#27F4D2" },
  { pos: 7, name: "Carlos Sainz", team: "williams", points: 0, color: "#64C4FF" },
  { pos: 8, name: "Fernando Alonso", team: "astonmartin", points: 0, color: "#229971" },
  { pos: 9, name: "Pierre Gasly", team: "alpine", points: 0, color: "#FF87BC" },
  { pos: 10, name: "Yuki Tsunoda", team: "rb", points: 0, color: "#6692FF" }
];

const CONSTRUCTOR_STANDINGS = [
  { pos: 1, name: "Scuderia Ferrari", points: 0, color: "#E8002D" },
  { pos: 2, name: "McLaren F1 Team", points: 0, color: "#FF8000" },
  { pos: 3, name: "Red Bull Racing", points: 0, color: "#3671C6" },
  { pos: 4, name: "Mercedes-AMG", points: 0, color: "#27F4D2" },
  { pos: 5, name: "Williams Racing", points: 0, color: "#64C4FF" },
  { pos: 6, name: "Aston Martin", points: 0, color: "#229971" },
  { pos: 7, name: "Racing Bulls", points: 0, color: "#6692FF" },
  { pos: 8, name: "Haas F1 Team", points: 0, color: "#B6BABD" },
  { pos: 9, name: "Alpine F1 Team", points: 0, color: "#FF87BC" },
  { pos: 10, name: "Kick Sauber", points: 0, color: "#52E252" }
];